version: '3'
services:
  carousel:
    container_name: carousel
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/src/app'
    ports: ['3001:3001']
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - './database'
    ports: ['27017:27017']